# Generated by Django 5.2.17 on 2026-10-09 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('blood_group', models.CharField(blank=True, default='', max_length=10)),
                ('vision', models.CharField(blank=True, default='', max_length=60)),
                ('hearing', models.CharField(blank=True, default='', max_length=60)),
                ('general_condition', models.CharField(blank=True, default='', max_length=120)),
                ('allergies', models.TextField(blank=True, default='')),
                ('chronic_conditions', models.TextField(blank=True, default='')),
                ('medications', models.TextField(blank=True, default='')),
                ('physical_exam_notes', models.TextField(blank=True, default='')),
                ('examined_by', models.CharField(blank=True, default='', max_length=160)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='FINAL', max_length=12)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='people.student')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
    ]
