# Generated by Django 5.2.17 on 2026-09-24 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('MEETING', 'Meeting'), ('VISIT', 'Visit'), ('FOLLOW_UP', 'Follow Up')], db_index=True, max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(blank=True, choices=[('NO_ANSWER', 'No Answer'), ('LEFT_MESSAGE', 'Left Message'), ('CONTACTED', 'Contacted'), ('NOT_INTERESTED', 'Not Interested'), ('BOOKED_VISIT', 'Booked Visit'), ('OTHER', 'Other')], default='', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('REFERRAL', 'Referral'), ('WEBSITE', 'Website'), ('ADMISSIONS', 'Admissions'), ('SOCIAL_MEDIA', 'Social Media'), ('EXISTING_PARENT', 'Existing Parent'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('ARCHIVED', 'Archived')], db_index=True, default='NEW', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('opt_in_sms', models.BooleanField(default=True)),
                ('opt_in_email', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], db_index=True, default='TODO', max_length=12)),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(blank=True, default='', max_length=200)),
                ('parent_name', models.CharField(blank=True, default='', max_length=200)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=20)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('visit_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='SCHEDULED', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['visit_date'],
            },
        ),
    ]
