# Generated by Django 5.2.17 on 2026-09-24 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('hr', '0002_initial'),
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='schools.term'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='people.student'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('school_class', 'attendance_date'), name='uq_attendance_session_day'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='uq_employee_attendance_day'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'session'], name='idx_student_attendance'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='uq_student_session'),
        ),
    ]
