# Generated by Django 5.2.17 on 2026-09-24 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, upload_to='uploads/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PROFILE_PHOTO', 'Profile Photo'), ('ADMISSION_DOCUMENT', 'Admission Document'), ('ASSIGNMENT_ATTACHMENT', 'Assignment Attachment'), ('LEARNING_RESOURCE', 'Learning Resource'), ('GALLERY_MEDIA', 'Gallery Media'), ('PAYSLIP', 'Payslip'), ('RECEIPT', 'Receipt'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('stored_path', models.CharField(blank=True, default='', max_length=500)),
                ('linked_type', models.CharField(blank=True, default='', max_length=120)),
                ('linked_id', models.UUIDField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
